/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.CadastroExercicio;
import Controller.CadastroExercicioController;

/**
 *
 * @author Pichau
 */
public class FraltExercicios extends javax.swing.JDialog {

    public FraltExercicios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    private String identificacao;

    public void setIdentificacao(String identificacao) {
        this.identificacao = identificacao;
        carregarExercicio(identificacao); // carrega os dados do exercício
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblIdentificacao = new javax.swing.JLabel();
        lblFuncao = new javax.swing.JLabel();
        lblEquipamento = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        lblTipodeExercicio = new javax.swing.JLabel();
        edtTipodeExercicio = new javax.swing.JTextField();
        edtfuncao = new javax.swing.JTextField();
        edtNome = new javax.swing.JTextField();
        edtEquipamento = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        edtcodigo = new javax.swing.JTextField();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("Alterar exercícios");

        lblIdentificacao.setBackground(new java.awt.Color(51, 255, 255));
        lblIdentificacao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIdentificacao.setForeground(new java.awt.Color(102, 255, 255));
        lblIdentificacao.setText("Código:");

        lblFuncao.setBackground(new java.awt.Color(102, 255, 255));
        lblFuncao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFuncao.setForeground(new java.awt.Color(102, 255, 255));
        lblFuncao.setText("Função:");

        lblEquipamento.setBackground(new java.awt.Color(102, 255, 255));
        lblEquipamento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEquipamento.setForeground(new java.awt.Color(102, 255, 255));
        lblEquipamento.setText("Equipamento:");

        btnSalvar.setBackground(new java.awt.Color(0, 0, 0));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(102, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblTipodeExercicio.setBackground(new java.awt.Color(102, 255, 255));
        lblTipodeExercicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTipodeExercicio.setForeground(new java.awt.Color(102, 255, 255));
        lblTipodeExercicio.setText("Tipo de exercício:");

        edtfuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtfuncaoActionPerformed(evt);
            }
        });

        lblNome.setBackground(new java.awt.Color(51, 255, 255));
        lblNome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(102, 255, 255));
        lblNome.setText("Nome:");

        edtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtcodigoActionPerformed(evt);
            }
        });

        btnFechar.setBackground(new java.awt.Color(0, 0, 0));
        btnFechar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(102, 255, 255));
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTipodeExercicio)
                                        .addGap(18, 18, 18)
                                        .addComponent(edtTipodeExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblNome)
                                        .addGap(18, 18, 18)
                                        .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblIdentificacao)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(edtcodigo))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblFuncao)
                                            .addGap(18, 18, 18)
                                            .addComponent(edtfuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(6, 6, 6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSalvar)
                                    .addComponent(lblEquipamento))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(edtEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                                        .addComponent(btnFechar))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentificacao)
                    .addComponent(edtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncao)
                    .addComponent(edtfuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipodeExercicio)
                    .addComponent(edtTipodeExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEquipamento)
                    .addComponent(edtEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnFechar))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        int id = Integer.parseInt(edtcodigo.getText());

        //  busca o exercício atual no banco
        CadastroExercicioController controller = new CadastroExercicioController();
        CadastroExercicio exercicioAtual = controller.buscarPorId(id);

        if (exercicioAtual == null) {
            JOptionPane.showMessageDialog(null, "Exercício não encontrado no banco.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // atualiza
        String nome = edtNome.getText().trim();
        String funcao = edtfuncao.getText().trim();
        String tipoDeExercicio = edtTipodeExercicio.getText().trim();
        String equipamento = edtEquipamento.getText().trim();

        if (!nome.isEmpty()) {
            exercicioAtual.setNome(nome);
        }
        if (!funcao.isEmpty()) {
            exercicioAtual.setFuncao(funcao);
        }
        if (!tipoDeExercicio.isEmpty()) {
            exercicioAtual.setTipoDeExercicio(tipoDeExercicio);
        }
        if (!equipamento.isEmpty()) {
            exercicioAtual.setEquipamento(equipamento);
        }

        // envia pro banco
        boolean sucesso = controller.alterarExercicio(exercicioAtual);

        if (sucesso) {
            JOptionPane.showMessageDialog(null, "Exercício alterado com sucesso.");
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao alterar o exercício.", "Erro", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnSalvarActionPerformed

    private void edtfuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtfuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtfuncaoActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
        FrMenu telaMenu = new FrMenu(null, true);
        telaMenu.setVisible(true);

    }//GEN-LAST:event_btnFecharActionPerformed

    private void edtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtcodigoActionPerformed


    }//GEN-LAST:event_edtcodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FraltExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FraltExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FraltExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FraltExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FraltExercicios dialog = new FraltExercicios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtEquipamento;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtTipodeExercicio;
    private javax.swing.JTextField edtcodigo;
    private javax.swing.JTextField edtfuncao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEquipamento;
    private javax.swing.JLabel lblFuncao;
    private javax.swing.JLabel lblIdentificacao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTipodeExercicio;
    // End of variables declaration//GEN-END:variables

    private void carregarExercicio(String identificacao) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
